# Generated by Django 4.1.6 on 2023-10-08 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cryption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('start_key', models.IntegerField()),
                ('key_increment', models.IntegerField()),
                ('key_increments_increment', models.IntegerField()),
                ('encrypted_message', models.TextField()),
            ],
        ),
    ]
