# Generated by Django 4.1.6 on 2023-10-08 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encrypt_decrypt_app', '0004_alter_cryption_encrypted_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryption',
            name='encrypted_message',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
